### PR TITLE
Added vultr provider

### PR DESCRIPTION
**Pull request by willseward**

### CODE REVIEW

**Comment by janeczku** [comment]
Thanks @willseward. I'll merge this soon. I am curious: What's your experience with Vultr's DNS service?

**Comment by willseward** [comment]
Thanks, @janeczku 

I'm not sure yet. I'm about to move some infrastructure over there from DO, so I'll circle back to you on that one... Why do you ask?

**Comment by janeczku** [comment]
@willseward Just curious about reliability.

**Comment by willseward** [comment]
@janeczku FWIW, I didn't end up using Vultr for DNS. I switched to Cloudflare.

**Pull request merged**
